# Generated by Django 5.1.6 on 2025-03-07 11:20

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[comments.models.validate_image, comments.models.validate_txt_file]),
        ),
    ]
