# Generated by Django 5.1.6 on 2025-03-07 16:00

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[comments.models.validate_file]),
        ),
    ]
